name: flutter_bus
description: Everyone home safely and efficiently from school.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.1.1

  flutter_gen: any
  web_socket_channel: ^3.0.0
  provider: ^6.1.2
  introduction_screen: ^3.1.14
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^11.0.0
  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
# #docregion generate
  # Enable generation of localized Strings from arb files.
  generate: true
# #enddocregion generate

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/ca/
